"""Generated by utils/cgit/cgit_util_generate_admin_file on 2022-01-24 14:43:25.002243"""

from django.contrib import admin
from .models import (
    InAppNotification,
    NotificationMapping,
    AbstractEmail,
    Email,
    EmailArchive,
    EmailThread,
    BatchID,
    Snooper,
    EmailBatchRBAC,
    BlockNotification,
    RealtimeNotificationHeader,
    RealtimeNotification,
    EmailAttachment,
    UnregisteredBlockedEmail,
)
from accounts.models import User


@admin.register(InAppNotification)
class InAppNotificationAdmin(admin.ModelAdmin):
    """Admin class for model InAppNotification"""

    search_fields = ("member",)
    autocomplete_fields = [
        "member",
    ]


@admin.register(NotificationMapping)
class NotificationMappingAdmin(admin.ModelAdmin):
    """Admin class for model NotificationMapping"""

    search_fields = ("member",)
    autocomplete_fields = [
        "member",
    ]


@admin.register(AbstractEmail)
class AbstractEmailAdmin(admin.ModelAdmin):
    """Admin class for model AbstractEmail"""

    autocomplete_fields = [
        "member",
        "sender",
    ]


@admin.register(Snooper)
class SnooperAdmin(admin.ModelAdmin):
    """Admin class for model Snooper"""

    autocomplete_fields = [
        "batch_id",
    ]


@admin.register(EmailBatchRBAC)
class EmailBatchRBACAdmin(admin.ModelAdmin):
    """Admin class for model EmailBatchRBAC"""

    autocomplete_fields = [
        "batch_id",
        "meta_sender",
        "meta_organisation",
    ]


@admin.register(BlockNotification)
class BlockNotificationAdmin(admin.ModelAdmin):
    """Admin class for model BlockNotification"""

    autocomplete_fields = [
        "member",
    ]


@admin.register(RealtimeNotificationHeader)
class RealtimeNotificationHeaderAdmin(admin.ModelAdmin):
    """Admin class for model RealtimeNotificationHeader"""

    search_fields = ("admin",)
    autocomplete_fields = [
        "admin",
    ]


@admin.register(RealtimeNotification)
class RealtimeNotificationAdmin(admin.ModelAdmin):
    """Admin class for model RealtimeNotification"""

    search_fields = ("member__first_name", "member__last_name")
    autocomplete_fields = [
        "header",
        "member",
        "admin",
    ]


@admin.register(BatchID)
class BatchIDAdmin(admin.ModelAdmin):
    """Admin class for model BatchID"""

    search_fields = ["batch_id"]


@admin.register(EmailAttachment)
class EmailAttachmentAdmin(admin.ModelAdmin):
    """Admin class for model EmailAttachment"""

    search_fields = ("member", "organisation")
    autocomplete_fields = [
        "member",
        "organisation",
    ]


@admin.register(UnregisteredBlockedEmail)
class UnregisteredBlockedEmailAdmin(admin.ModelAdmin):
    """Admin class for model UnregisteredBlockedEmail"""

    autocomplete_fields = [
        "un_registered_user",
    ]


admin.site.register(Email)
admin.site.register(EmailArchive)
admin.site.register(EmailThread)
