# Generated by Django 5.2.1 on 2025-10-17 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0079_auto_20240925_1641"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membertransaction",
            name="club_session_id",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="organisationtransaction",
            name="club_session_id",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
