# Generated by Django 5.2.8 on 2026-03-28 09:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0094_alter_organisation_results_email_message"),
        ("payments", "0081_organisationtransaction_xero_invoice"),
        ("xero", "0008_alter_xerocredentials_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="membertransaction",
            index=models.Index(
                fields=["member", "-created_date"], name="pmtxn_member_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organisationtransaction",
            index=models.Index(
                fields=["organisation", "-created_date"], name="porgtxn_org_date_idx"
            ),
        ),
    ]
