"""Generated by utils/cgit/cgit_util_generate_admin_file on 2022-01-24 14:41:34.741858"""

from django.contrib import admin
from .models import Incident, IncidentLineItem, Attachment, NotifyUserByType


@admin.register(Incident)
class IncidentAdmin(admin.ModelAdmin):
    """Admin class for model Incident"""

    autocomplete_fields = [
        "reported_by_user",
        "assigned_to",
    ]
    list_display = ("reported_by_user", "reported_by_email", "description")
    search_fields = ("reported_by_user", "reported_by_email", "description")


@admin.register(IncidentLineItem)
class IncidentLineItemAdmin(admin.ModelAdmin):
    """Admin class for model IncidentLineItem"""

    autocomplete_fields = [
        "incident",
        "staff",
    ]
    list_display = ("staff", "created_date", "incident")
    search_fields = ("staff", "description", "incident")


@admin.register(Attachment)
class AttachmentAdmin(admin.ModelAdmin):
    """Admin class for model Attachment"""

    autocomplete_fields = [
        "user",
        "incident",
    ]


@admin.register(NotifyUserByType)
class NotifyUserByTypeAdmin(admin.ModelAdmin):
    """Admin class for model NotifyUserByType"""

    autocomplete_fields = [
        "staff",
    ]
