# Generated by Django 5.2.1 on 2025-09-15 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0120_congress_results_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="congress",
            name="allow_edit_of_old_congress",
            field=models.BooleanField(default=False),
        ),
    ]
