# Generated by Django 5.2.12 on 2026-04-14 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0121_congress_allow_edit_of_old_congress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evententry",
            name="free_format_answer",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Free Format Answer"
            ),
        ),
    ]
