#!/bin/bash
# Restore a local database backup

# Variables
if [[ $# -ne 2 ]]; then
  echo ""
  echo "Usage: $0 db_name db_file"
  echo ""
  exit 1
fi

RDS_DB_NAME=$1
DB_FILE=$2

# load database
cat << EOF > /tmp/drop_db
\c postgres
SELECT pg_terminate_backend(pid)
FROM pg_stat_activity
WHERE datname = '$LOCAL_DB_NAME';
drop database IF EXISTS $RDS_DB_NAME;
create database $RDS_DB_NAME with owner cobalt;
EOF

psql "$RDS_DB_NAME" </tmp/drop_db
if ! pg_restore -d "$RDS_DB_NAME" --no-owner --no-privileges --role=cobalt -v "$DB_FILE"
then
  echo "An error occurred"
fi

./manage.py migrate
export RDS_DB_NAME=prod_load
./manage.py sanitise_production_data_for_testing