#!/bin/bash
# Restore a local database backup

source utils/cgit/_cgit_db_helper

# Variables
if [[ $# -ne 2 ]]; then
  echo ""
  echo "Usage: $0 db_name db_file"
  echo ""
  exit 1
fi

RDS_DB_NAME=$1
DB_FILE=$2

# Drop, recreate, then restore
drop_and_recreate_db "$RDS_DB_NAME" "cobalt"
if ! pg_restore -d "$RDS_DB_NAME" --no-owner --no-privileges --role=cobalt -v "$DB_FILE"
then
  echo "An error occurred"
fi

./manage.py migrate
export RDS_DB_NAME=prod_load
./manage.py sanitise_production_data_for_testing