#!/bin/bash

# about: compare the code on two branches
# param: new_branch [branch]
# param: old_branch [branch]
# param: --ignore PATTERN

source utils/cgit/_cgit_include_vars

# Compare 2 branches
OLD=$1
NEW=$2

if [ $# -lt 2 ]
then
  echo "Usage: $0 new_branch old_branch --ignore 'pattern'"
  echo ""
  echo "e.g. $0 develop release/1.1.1 --ignore '^static'"
  echo "e.g. $0 develop release/1.1.2 --ignore '^static|html$|docs'"
  exit
fi

if [[ -z $(git status -s) ]]
then
  # Nothing
  echo ""
else
  printf "\n\n${BLUE}WARNING!!!${NC}: ${RED}Unsaved changes in current branch.${NC} These won't be included.\n\n"
  git status
  read -p "Press key to continue..." -n1 -s
  echo ""
  echo "Running..."
fi

# Format the HTML Template
cp utils/cgit/tools/cgit_template.html /tmp/temp.html
# Use # as sed character since / will be in release branch
sed -i -e "s#!!BRANCH!!#$OLD#g" /tmp/temp.html
sed -i -e "s#!!OTHERBRANCH!!#$NEW#g" /tmp/temp.html

if [ $# -gt 2 ]
then
  DIFF=$(git diff "$NEW" "$OLD" --name-only | grep -Ev "$4" | xargs git diff "$NEW" --)
  FILE_COUNT=$(git diff "$NEW" "$OLD" --name-only | grep -Ev "$4" | wc -l | tr -d ' ')
  STAT=$(git diff "$NEW" "$OLD" --name-only | grep -Ev "$4" | xargs git diff "$NEW" --shortstat --)
else
  DIFF=$(git diff -w "$NEW" "$OLD")
  FILE_COUNT=$(git diff -w "$NEW" "$OLD" --name-only | wc -l | tr -d ' ')
  STAT=$(git diff -w "$NEW" "$OLD" --shortstat)
fi

INSERTIONS=$(echo "$STAT" | grep -oE '[0-9]+ insertion' | grep -oE '[0-9]+' || echo 0)
DELETIONS=$(echo "$STAT" | grep -oE '[0-9]+ deletion' | grep -oE '[0-9]+' || echo 0)
TOTAL_LINES=$(( ${INSERTIONS:-0} + ${DELETIONS:-0} ))

printf "\n${BLUE}Summary:${NC} ${GREEN}$FILE_COUNT files changed${NC}, ${GREEN}$TOTAL_LINES lines affected${NC} (${GREEN}+$INSERTIONS${NC} / ${RED}-$DELETIONS${NC})\n\n"

echo "$DIFF" | diff2html -i stdin -s side --su open --htmlWrapperTemplate /tmp/temp.html