#!/bin/bash

# about: full rebuild of the test database

source utils/cgit/_cgit_db_helper

# Variables
export RDS_DB_NAME=test
export DUMMY_DATA_COUNT=1

# Override the DB Name if passed as a parameter
if [ $# -eq 1 ]; then
  export RDS_DB_NAME=$1
fi

# Rebuild database
drop_and_recreate_db "$RDS_DB_NAME" "$CGIT_ENV"

# build database using test data directory - not currently using core
utils/aws/rebuild_test_database_subcommands.sh

# Dump database for quick access
pg_dump test > ~/test.db