#!/bin/bash

# about: runs unit, integration and smoke tests and produces coverage report

# We don't want to sleep so run caffeinate (only works on a Mac)
echo "#############################################"
echo "#                                           #"
echo "# Running caffeinate to keep computer alive #"
echo "#                                           #"
echo "# Do something else for a few minutes       #"
echo "#                                           #"
echo "#############################################"

# -d keeps the display on
caffeinate -d _cgit_dev_test_all_sub $*