#!/bin/bash

# about: full rebuild of the local development database

source utils/cgit/_cgit_db_helper

# Variables
export DUMMY_DATA_COUNT=20

# Rebuild database
drop_and_recreate_db "$RDS_DB_NAME" "$CGIT_ENV"

# build database using core test data directory
utils/aws/rebuild_test_database_subcommands.sh