#!/bin/bash

# about: Copy Test or UAT database to development

if [ $# -ne 1 ];then
  echo ""
  echo ""
  echo "Usage: $0 env"
  echo "e.g. $0 cobalt-test-black"
 exit 1
fi

ENV=$1
DUMP_FILE="/tmp/dbdump"

# Prevent pager output from AWS CLI
export AWS_PAGER=""

# Override some vars
export RDS_DB_NAME=$(echo $ENV | tr -d "-")

# get variables from EB
export PGPASSWORD=$(eb printenv "$ENV" | grep RDS_PASSWORD | awk '{print $3}')
POSTGRES_DB=$(eb printenv "$ENV" | grep RDS_DB_NAME | awk '{print $3}')
REMOTE_HOSTNAME=$(eb printenv "$ENV" | grep RDS_HOST | awk '{print $3}')

# Hardcode the ones that are unlikely to change and aren't passwords
POSTGRES_USER="postgres"

# Update the firewall rule so we can connect if local IP had changed
printf "Getting your IPv4 address...\n"
MY_IP=$(curl ipinfo.io/ip)

aws ec2 modify-security-group-rules \
    --group-id sg-e6b3fd98 \
    --security-group-rules SecurityGroupRuleId=sgr-0f0e494ea840a7a52,SecurityGroupRule="{Description='Off Sys Backup',IpProtocol=-1,CidrIpv4=$MY_IP/32}"

# Dump database - requires firewall rule to be in place
#pg_dump --exclude-table-data "public.notifications_abstractemail" --exclude-table-data "public.post_office_*" -h $REMOTE_HOSTNAME -p 5432 -d $POSTGRES_DB -U $POSTGRES_USER -F c -b -v -f $DUMP_FILE
pg_dump -h "$REMOTE_HOSTNAME" -p 5432 -d "$POSTGRES_DB" -U "$POSTGRES_USER" -F c -b -v -f "$DUMP_FILE"

# drop old database
echo "Loading database, dropping old DB..."
cat << EOF > /tmp/drop_db_copy
\c postgres
SELECT pg_terminate_backend(pid)
FROM pg_stat_activity
WHERE datname = $RDS_DB_NAME;
drop database IF EXISTS $RDS_DB_NAME;
create database $RDS_DB_NAME with owner cobalt;
EOF

psql </tmp/drop_db_copy

# Load the database
echo "Loading the data, this will take a while..."
pg_restore -h localhost -p 5432 -U guthrie -d "$RDS_DB_NAME" --no-owner --no-privileges --role=cobalt -v $DUMP_FILE

# sanitise data
./manage.py migrate
./manage.py sanitise_production_data_for_testing

echo ""
echo "If there are no errors above you should now have a sanitised copy"
echo "of the database for $ENV locally as $RDS_DB_NAME"
