#!/bin/bash

# about: runs unit tests
# Pass a parameter to include coverage output

# Variables
export RDS_DB_NAME=test

_cgit_test_handle_db

# Only run coverage if called by the wrapper script
if [ $# -eq 1 ]
then
  coverage run -p ./manage.py run_tests_unit
else
  ./manage.py run_tests_unit
fi