#!/bin/bash
# Menu command for cgit

TEMP_FILE=/tmp/cgit_cmd
rm -f $TEMP_FILE

# list cgit commands and get the high level name eg test, uat, util
for FILE_AND_PATH in utils/cgit/cgit_*; do
  FILE_NAME=$(basename "$FILE_AND_PATH")
  # Get high level area e.g. cgit_dev_start - we want dev
  echo "$FILE_NAME" | awk -F '_' '{print $2}' >> $TEMP_FILE
done

# Get unique commands from file
cat $TEMP_FILE | sort -u


rm $TEMP_FILE