#!/bin/bash

# about: runs smoke tests

# Variables
PORT=8088
export RDS_DB_NAME=test
export DUMMY_DATA_COUNT=1

# Kill manage.py if running
lsof -i tcp:$PORT | awk 'NR!=1 {print $2}' | xargs kill

# Kill old chromedrivers
pkill -TERM -f chromedriver

# Rebuild database
cat << EOF > /tmp/drop_db
\c postgres
drop database IF EXISTS $RDS_DB_NAME;
create database $RDS_DB_NAME with owner cobalt;
EOF

psql test </tmp/drop_db
psql test < ~/test.db >/dev/null

open . utils/cgit/tools/test_manage_short.terminal

# Wait for port to be open
echo "Waiting for Webserver to start..."
while ! nc -z 127.0.0.1 $PORT; do
  sleep 0.1
done
echo "Starting..."

COMMAND="./manage.py smoke_test --base_url=http://127.0.0.1:8088 --show"

# Only run coverage if called by the wrapper script
if [ $# -eq 1 ]
then
  COMMAND="coverage run -p $COMMAND"
fi

echo "Running tests in tests/scripts/test_suite"

# Keep score in a file
rm -f /tmp/smoke_test_outcome.txt

for FILE_AND_PATH in tests/scripts/test_suite/*; do
  FILE_NAME=$(basename "$FILE_AND_PATH")
  echo "Processing file: $FILE_NAME"
  $COMMAND --script "test_suite/$FILE_NAME"
  echo "$FILE_NAME $?" >> /tmp/smoke_test_outcome.txt
done

# Stop the django server
lsof -i tcp:$PORT | awk 'NR!=1 {print $2}' | xargs kill -SIGINT