#!/bin/bash

# about: performs checks (mostly questions) before deploying a release

source utils/cgit/_cgit_include_vars

STEPS=6

# Function to get response from user, a beautiful piece of shell scripting
get_response () {
# $1 = step no, $2 = message
    printf "${YELLOW}[${1}/${STEPS}] ${2}${NC}"
    read -r -p " [Y/n] " response
    if [ "$response" == "" ]
    then
      response="Y"
     fi
    if ! [[ "$response" =~ ^([yY][eE][sS]|[yY])$ ]]
    then
        echo ""
        echo "Step failed - exiting"
        echo ""
        exit
    fi
}

echo "starting..."
THIS_BRANCH=$(git branch --show-current)
PROD_BRANCH=$(cgit_util_branch_for_environment production| tail -1)
# Check we have the latest prod branch
git fetch origin $PROD_BRANCH:$PROD_BRANCH
clear
printf "${RED}###########################################################\n"
echo "#                                                         #"
echo "#           Pre-Release Checks for Production             #"
echo "#           =================================             #"
echo "#                                                         #"
echo "#  Make sure you are on the branch you intend to release  #"
echo "#                                                         #"
echo "###########################################################"
printf "${NC}\n\n"
printf "  You are on branch    : ${YELLOW}${THIS_BRANCH}${NC}\n"
printf "  Production is running: ${RED}${PROD_BRANCH}${NC}\n\n"


MODELS=$(git diff "$THIS_BRANCH" "$PROD_BRANCH" --name-only | grep models.py)

if [ $? -eq 1 ]
then
  echo "There are no model changes in this release."
  echo ""
else
  echo "There are model changes in this release:"
  echo "$MODELS"
  echo
fi

# Backups
get_response 1 "Did backups completed successfully?"

# Prod copy and smoke test
echo ""
echo "#########################################"
echo "Running migrations to update database..."
export RDS_DB_NAME=prod_load
./manage.py migrate
echo "Sanitising production data for smoke test..."
cgit_dev_run_prod_copy
echo ""
echo "Running smoke test against prod_load..."
cgit_dev_test_smoke
if [ $? -ne 0 ]; then
  get_response 2 "Smoke test had failures. Are you happy to continue?"
else
  echo "[2/$STEPS] Smoke test passed."
fi

# Compare versions
echo ""
echo "#########################################"
echo "Comparing this version with production..."
cgit_util_compare_env production
get_response 3 "Have you reviewed the changes above and are happy to proceed?"
get_response 4 "Did you review any changes to models.py that could prevent rollback?"

# Rollback
echo "You can test the rollback to see if the code works with any database changes."
echo "To do this simple checkout the version of code running in production "
get_response 5 "Are you happy?"

# Final checks
get_response 6 "Have you checked if there are any environment variables that still need to be applied to production?"

echo ""
echo "Ok, you are good to do the release."
echo "Use cgit_prod_publish to deploy your code."
echo "Good luck!"
echo ""