#!/bin/bash

# about: deploy this branch to an environment

# Sometimes you want to deploy code without going through proper cgit processes
# This does it so that at least the proper label is applied

BRANCH=`git branch --show-current`

  if [ $# -ne 1 ];then
    echo ""
    echo ""
    echo "Usage: $0 env"
    echo "e.g. $0 cobalt-test-white"
   exit 1
  fi

ENV=$1

if [[ -z $(git status -s) ]]
then

  if echo $ENV | grep test >/dev/null
  then
    echo ""
    echo "##################################"
    echo "# PRODUCTION!!! Are you mad?     #"
    echo "##################################"
    echo ""
    read -p "Press key to continue..." -n1 -s
  fi

   DATE=$(date '+%a_%d/%m/%Y_%H:%M:%S')
   echo "Running eb deploy -m '$BRANCH@$DATE' $ENV"
   eb deploy -m "$BRANCH@$DATE" $ENV
else
  echo ""
  echo ""
  echo "There are uncommitted changes or other problems with your git status. See below."
  echo ""
  echo ""
  git status
  echo ""
  echo ""
fi