#!/bin/bash

# about: runs unit and integration tests and produces coverage report

# reset coverage
coverage erase

# pass 2 parameters to get the coverage output
cgit_dev_test_unit with coverage

# Only seems to work if running in the foreground, add --show for now
cgit_dev_test_integration --coverage --show
coverage combine
coverage html
open htmlcov/index.html
coverage erase