#!/bin/bash

# about: deploy changes to UAT

source utils/cgit/_cgit_include_vars

BRANCH=$(git branch --show-current)

if [ "$BRANCH" != "develop" ]
then
  echo ""
  echo "################################################################"
  echo "# Warning: You are not on the develop branch. The branch that  #"
  echo "# will be deployed to UAT is develop, not your current branch. #"
  echo "################################################################"
fi

echo ""
echo ""
echo "Ready to Deploy to UAT."
echo ""
echo "First we will give this release a new version number."
echo "Then we will create a release branch and deploy it to UAT."
echo ""

OLDRELEASE=$(grep VER $CGIT_ENV/version.py | awk '{print $3}' | tr -d "\"")

echo "Last release was $OLDRELEASE"
echo ""
echo -n "Release Number: "
read RELEASE
echo "$RELEASE"

echo ""
echo "Switching to develop branch..."
echo ""

git checkout develop
if [ $? -ne 0 ];then
  exit 1
fi

echo ""
echo "Ensuring develop branch is up to date..."
echo ""
git pull origin develop
if [ $? -ne 0 ];then
   exit 1
fi

echo ""
echo "Running unit tests before creating release..."
echo ""
cgit_dev_test_unit
if [ $? -ne 0 ]; then
  echo ""
  echo "Unit tests failed. Fix the failures before releasing to UAT."
  exit 1
fi
echo "Tests passed."

echo ""
echo "Updating release version in $CGIT_ENV code..."
echo ""

echo "COBALT_VERSION = \"$RELEASE\"" > $CGIT_ENV/version.py

echo ""
echo "Saving version number to develop..."
echo ""

git add -A
if [ $? -ne 0 ];then
  exit 1
fi

# Unless something stupid is put in for a release number this wont fail the pre-commits
git commit -a -m "Updating release version to $RELEASE"
git push origin develop

echo ""
echo "Creating release branch..."
echo ""

git checkout -b release/"$RELEASE"
if [ $? -ne 0 ];then
  echo "There is a problem with the branch."
  echo "If you need to delete a local branch use: git branch -d release/$RELEASE"
  echo "Use -D to force."
  echo ""
  echo "If you need to delete a remote branch use git push -d origin release/$RELEASE"
  echo ""

  exit 1
fi

echo ""
echo "Pushing release branch to github..."
echo ""

git push origin release/"$RELEASE"
if [ $? -ne 0 ];then
  exit 1
fi

echo ""
echo "Deploying to UAT server..."
echo ""

UATENV=$(eb list | grep $COBALT_UAT)
UATNUM=$(eb list | grep $COBALT_UAT | wc -l)

if [ "$UATNUM" -eq 1 ]
then
    # Capture current version for rollback hint
    PREV_VERSION=$(aws elasticbeanstalk describe-environments \
      --environment-names "$UATENV" \
      --query 'Environments[0].VersionLabel' \
      --output text 2>/dev/null)

    # Get number of EC2 instances running. We want at least 2
    utils/cgit/_cgit_scale_environment_for_deployment $UATENV
    ec2_instances=$?

  echo "Original instance number was $ec2_instances"

   echo "Deploying code to $UATENV..."
   DATE=$(date '+%a_%d/%m/%Y_%H:%M:%S')
   eb deploy -m "release/$RELEASE@$DATE" $UATENV

   if [ "$ec2_instances" = "1" ]
    then

      echo "Restoring instance number to $ec2_instances. Could take a few minutes..."

      eb scale "$ec2_instances" "$UATENV"

   fi

   echo ""
   echo "Deployment of release/$RELEASE to UAT complete."
   if [ -n "$PREV_VERSION" ]; then
     echo ""
     echo "Previous version was: $PREV_VERSION"
     echo "To roll back if needed:"
     echo "  eb deploy -l \"$PREV_VERSION\" $UATENV"
   fi
   echo ""

else
   echo "Cannot deploy to UAT, found more than one UAT environment."
   echo $UATENV
fi

