#!/bin/bash

# about: runs smoke tests

source utils/cgit/_cgit_include_vars

# Variables
PORT=8088
export RDS_DB_NAME=test
export DUMMY_DATA_COUNT=1

_cgit_test_start --django

COMMAND="./manage.py smoke_test --base_url=http://127.0.0.1:$PORT --show --silent"

# Only run coverage if called by the wrapper script
if [ $# -eq 1 ]
then
  COMMAND="coverage run -p $COMMAND"
fi

echo "Running tests in tests/scripts/test_suite..."
echo ""

# Keep score in a file
rm -f /tmp/smoke_test_outcome.txt

# Add start time as first row
date +"%s" > /tmp/smoke_test_outcome.txt

# Loop through the test files
for FILE_AND_PATH in tests/scripts/test_suite/*; do
  FILE_NAME=$(basename "$FILE_AND_PATH")

  # run command
  $COMMAND --script "test_suite/$FILE_NAME"

  # get status
  rc=$?

  # Save outcome in file
  echo "$FILE_NAME $rc" >> /tmp/smoke_test_outcome.txt

  # Print to screen
  printf "%-50s" "$FILE_NAME"
  if [ "$rc" == "0" ]; then
    printf "${YELLOW}Pass${NC}\n"
  else
    printf "${RED}Fail${NC}\n"
  fi
done

# Create summary HTML report

./manage.py create_smoke_test_report

# Tidy up
_cgit_test_finish