#!/bin/bash

# about: rebuild local database for development

# Stop Django if running
lsof -i tcp:8000 | awk 'NR!=1 {print $2}' | xargs kill -SIGINT

# Reload database
cat << EOF > /tmp/drop_db
\c postgres

SELECT pg_terminate_backend(pg_stat_activity.pid)
FROM pg_stat_activity
WHERE pg_stat_activity.datname = 'cobalt'
  AND pid <> pg_backend_pid();

drop database IF EXISTS cobalt;
create database cobalt with owner cobalt;
EOF

psql test </tmp/drop_db



utils/aws/rebuild_test_database_subcommands.sh