#!/bin/bash

# about: runs integration tests. --show --coverage --debug --module [module]

# Get arguments
SHOW=0
COVERAGE=0
MODULE=0
DEBUG_WEB=0

while [[ $# -gt 0 ]]; do
  case $1 in
    -s|--show)
      SHOW=1
      shift # past argument
      ;;
    -d|--debug)
      DEBUG_WEB=1
      shift # past argument
      ;;
    -c|--coverage)
      COVERAGE=1
      shift # past argument
      ;;
    -m|--module)
      MODULE="$2"
      shift # past argument
      shift # past value
      ;;
    -*|--*)
      echo "Unknown option $1"
      exit 1
      ;;
  esac
done

# Variables
PORT=8088
export RDS_DB_NAME=test
export DUMMY_DATA_COUNT=1
export DEBUG=OFF

# Common code to get ready
COMMAND="_cgit_test_start --stripe"
 if [ "$DEBUG_WEB" == "0" ]; then
   COMMAND="$COMMAND --django"
fi
$COMMAND

# Build run command
COMMAND=""

if [ $COVERAGE -eq 1 ]
  then
    COMMAND="coverage run -p"
fi

COMMAND="$COMMAND ./manage.py run_tests_integration --base_url http://127.0.0.1:$PORT"

if [ $SHOW -ne 1 ]
  then
    COMMAND="$COMMAND --headless true"
fi

if [ "$MODULE" != "0" ]
  then
    COMMAND="$COMMAND --single_test $MODULE"
fi

# run it
echo "Running: $COMMAND"
$COMMAND

_cgit_test_finish