#!/bin/bash

# Pull current branch and generally sync things up

BRANCH=$(git branch --show-current)

echo "#########################################"
echo "# Pulling current branch...             #"
echo "#########################################"
git pull origin $BRANCH
echo "..."

echo "#########################################"
echo "# Fetching everything remote...         #"
echo "#########################################"
git fetch origin
echo "..."

echo "#########################################"
echo "# Django ./manage.py migrate...         #"
echo "#########################################"
./manage.py migrate
echo "..."




