repos:
-   repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
    - id: black
      additional_dependencies: ['click==8.0.4']
      language_version: python3.7
-   repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
      additional_dependencies:
        - importlib-metadata<5.0
- repo: https://github.com/rtts/djhtml
  rev: v1.4.9
  hooks:
    - id: djhtml
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1  # Use the ref you want to point at
    hooks:
    -   id: debug-statements