# Generated by Django 5.2.8 on 2026-03-02 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0092_alter_memberclubdetails_latest_membership"),
        ("xero", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="XeroInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("xero_invoice_id", models.CharField(max_length=100, unique=True)),
                (
                    "invoice_number",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "invoice_type",
                    models.CharField(
                        choices=[
                            ("ACCREC", "Accounts Receivable"),
                            ("ACCPAY", "Accounts Payable"),
                        ],
                        default="ACCREC",
                        max_length=10,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("AUTHORISED", "Authorised"),
                            ("PAID", "Paid"),
                            ("VOIDED", "Voided"),
                        ],
                        default="AUTHORISED",
                        max_length=15,
                    ),
                ),
                ("reference", models.CharField(blank=True, default="", max_length=255)),
                ("date", models.DateField()),
                ("due_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="xero_invoices",
                        to="organisations.organisation",
                    ),
                ),
            ],
        ),
    ]
