# Generated by Django 5.2.8 on 2026-03-13 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("xero", "0002_xeroinvoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="xeroinvoice",
            name="online_invoice_url",
            field=models.URLField(blank=True, default=""),
        ),
    ]
