# Generated by Django 5.2.8 on 2026-03-13 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("xero", "0003_xeroinvoice_online_invoice_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="XeroLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("method", models.CharField(max_length=10)),
                ("url", models.CharField(max_length=500)),
                ("request_body", models.TextField(blank=True)),
                ("response_body", models.TextField(blank=True)),
                ("http_status_code", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("Success", "Success"), ("Failure", "Failure")],
                        max_length=10,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
