# Generated by Django 5.2.8 on 2026-03-15 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("xero", "0005_xeroinvoice_deferred_upload"),
    ]

    operations = [
        migrations.AddField(
            model_name="xeroinvoice",
            name="auto_record_payment",
            field=models.BooleanField(default=False),
        ),
    ]
