# Generated by Django 5.2.8 on 2026-03-25 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("xero", "0007_xeroinvoice_email_sent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="xerocredentials",
            options={"verbose_name_plural": "Xero credentials"},
        ),
    ]
