"""Generated by utils/cgit/cgit_util_generate_admin_file on 2022-01-24 14:54:06.307431"""

from django.contrib import admin
from .models import (
    Organisation,
    MembershipType,
    MemberMembershipType,
    ClubLog,
    MemberClubEmail,
    ClubTag,
    MemberClubTag,
    Visitor,
    OrganisationFrontPage,
    MiscPayType,
    OrgVenue,
    WelcomePack,
    OrgEmailTemplate,
    MemberClubDetails,
    MemberClubOptions,
    ClubMemberLog,
)


@admin.register(Organisation)
class OrganisationAdmin(admin.ModelAdmin):
    """Admin class for model Organisation"""

    autocomplete_fields = [
        "secretary",
        "last_updated_by",
    ]
    search_fields = ["name"]


@admin.register(MembershipType)
class MembershipTypeAdmin(admin.ModelAdmin):
    """Admin class for model MembershipType"""

    search_fields = [
        "organisation",
        "last_modified_by",
    ]
    autocomplete_fields = [
        "organisation",
        "last_modified_by",
    ]


@admin.register(MemberMembershipType)
class MemberMembershipTypeAdmin(admin.ModelAdmin):
    """Admin class for model MemberMembershipType"""

    autocomplete_fields = [
        "membership_type",
        "last_modified_by",
        "payment_method",
    ]

    search_fields = ["system_number"]


@admin.register(ClubLog)
class ClubLogAdmin(admin.ModelAdmin):
    """Admin class for model ClubLog"""

    autocomplete_fields = [
        "organisation",
        "actor",
    ]


@admin.register(MemberClubEmail)
class MemberClubEmailAdmin(admin.ModelAdmin):
    """Admin class for model MemberClubEmail"""

    autocomplete_fields = [
        "organisation",
    ]

    search_fields = [
        "email",
    ]


@admin.register(ClubTag)
class ClubTagAdmin(admin.ModelAdmin):
    """Admin class for model ClubTag"""

    search_fields = [
        "organisation",
    ]
    autocomplete_fields = [
        "organisation",
    ]


@admin.register(MemberClubTag)
class MemberClubTagAdmin(admin.ModelAdmin):
    """Admin class for model MemberClubTag"""

    autocomplete_fields = [
        "club_tag",
    ]


@admin.register(Visitor)
class VisitorAdmin(admin.ModelAdmin):
    """Admin class for model Visitor"""

    autocomplete_fields = [
        "organisation",
    ]


@admin.register(MiscPayType)
class MiscPayTypeAdmin(admin.ModelAdmin):
    """Admin class for model MiscPayType"""

    autocomplete_fields = [
        "organisation",
    ]


@admin.register(OrgVenue)
class OrgVenueAdmin(admin.ModelAdmin):
    """Admin class for model OrgVenue"""

    search_fields = [
        "organisation",
    ]

    autocomplete_fields = [
        "organisation",
    ]


@admin.register(WelcomePack)
class WelcomePackAdmin(admin.ModelAdmin):
    """Admin class for model WelcomePack"""

    search_fields = [
        "organisation",
        "template",
    ]

    autocomplete_fields = [
        "organisation",
        "template",
        "last_modified_by",
    ]


@admin.register(OrgEmailTemplate)
class OrgEmailTemplateAdmin(admin.ModelAdmin):
    """Admin class for model OrgEmailTemplate"""

    search_fields = [
        "organisation",
    ]

    autocomplete_fields = [
        "organisation",
        "last_modified_by",
    ]


@admin.register(MemberClubDetails)
class MemberClubDetailsAdmin(admin.ModelAdmin):
    """Admin class for model MemberClubDetails"""

    search_fields = [
        "club__name",
        "system_number",
        "email",
    ]

    autocomplete_fields = [
        "club",
        "latest_membership",
    ]


@admin.register(MemberClubOptions)
class MemberClubOptionsAdmin(admin.ModelAdmin):
    """Admin class for model MemberClubOptions"""

    search_fields = [
        "club__name",
        "user__last_name",
        "user__first_name",
    ]

    autocomplete_fields = [
        "club",
    ]


@admin.register(ClubMemberLog)
class ClubMemberLogAdmin(admin.ModelAdmin):
    """Admin class for model ClubMemberLog"""

    search_fields = [
        "club__name",
        "system_number",
    ]

    autocomplete_fields = [
        "club",
    ]


admin.site.register(OrganisationFrontPage)
