# Generated by Django 5.2.1 on 2025-08-16 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0071_remove_user_share_with_clubs"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="receive_member_to_member_emails",
            field=models.BooleanField(default=True),
        ),
    ]
