# Generated by Django 5.2.1 on 2025-11-04 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0072_user_receive_member_to_member_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='unregistereduser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='unregistereduser',
            name='old_mpc_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='old_mpc_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='unregistereduser',
            name='origin',
            field=models.CharField(choices=[('MPC', 'Masterpoints Centre Import'), ('MPCS', 'Masterpoints Centre Sync'), ('Pianola', 'Pianola Import'), ('CSV', 'CSV Import'), ('Manual', 'Manual Entry')], max_length=10, verbose_name='Origin'),
        ),
    ]
