# Generated by Django 5.2.8 on 2025-11-10 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0072_user_receive_member_to_member_emails"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useradditionalinfo",
            name="congress_view_filters",
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
