# Generated by Django 5.2.1 on 2025-11-04 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0073_unregistereduser_old_mpc_id_user_old_mpc_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unregistereduser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
