# Generated by Django 5.2.1 on 2025-11-13 02:14

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0073_alter_useradditionalinfo_congress_view_filters'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='covid_status',
        ),
        migrations.AddField(
            model_name='unregistereduser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='unregistereduser',
            name='old_mpc_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_abf_active',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='old_mpc_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('U', 'User'), ('N', 'Unregistered'), ('C', 'Contact')], default='U', max_length=1),
        ),
        migrations.AddField(
            model_name='useradditionalinfo',
            name='last_registration_invite_sent',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Registration Invite Sent'),
        ),
        migrations.AlterField(
            model_name='unregistereduser',
            name='origin',
            field=models.CharField(choices=[('MPC', 'Masterpoints Centre Import'), ('MPCS', 'Masterpoints Centre Sync'), ('Pianola', 'Pianola Import'), ('CSV', 'CSV Import'), ('Manual', 'Manual Entry')], max_length=10, verbose_name='Origin'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
