# Generated by Django 5.2.1 on 2025-10-30 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0073_unregistereduser_old_mpc_id_user_old_mpc_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unregistereduser",
            name="old_mpc_id",
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="old_mpc_id",
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
