# Generated by Django 5.2.1 on 2025-11-12 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0073_alter_useradditionalinfo_congress_view_filters'),
        ('accounts', '0073_unregistereduser_is_active_and_more'),
    ]

    operations = [
    ]
