# Generated by Django 5.2.1 on 2025-12-08 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0074_alter_user_managers_remove_user_covid_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identifier',
            field=models.CharField(default='NOTSET', max_length=10),
        ),
    ]
