# Generated by Django 5.2.1 on 2025-11-17 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0074_alter_user_managers_remove_user_covid_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('U', 'User'), ('N', 'Unregistered User'), ('C', 'Contact')], default='U', max_length=1),
        ),
    ]
