# Generated by Django 5.2.1 on 2025-11-12 01:50

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0074_merge_20251112_1249'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='covid_status',
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('U', 'User'), ('N', 'Unregistered'), ('C', 'Contact')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
