# Generated by Django 5.2.12 on 2026-04-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0075_user_identifier"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemcard",
            name="conv_4th_suit_game_force",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="systemcard",
            name="conv_4th_suit_one_round",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="systemcard",
            name="conv_defence_3nt",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="systemcard",
            name="conv_defence_opening_twos",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="systemcard",
            name="conv_defence_strong_1c",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="systemcard",
            name="conv_defence_strong_2c",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="systemcard",
            name="conv_lebensohl",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="systemcard",
            name="conv_multi_2d",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="systemcard",
            name="conv_nt_checkback",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="systemcard",
            name="conv_nt_checkback_priorities",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="systemcard",
            name="conv_other_2s",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="systemcard",
            name="conv_over_1nt_interference",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="systemcard",
            name="conv_rco_2s",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="systemcard",
            name="conv_takeout_4c_4d",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="systemcard",
            name="conv_takeout_4h",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="systemcard",
            name="conv_takeout_4s",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="systemcard",
            name="conv_unusual_nt",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="systemcard",
            name="slam_asking_bids",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="systemcard",
            name="slam_blackwood",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="systemcard",
            name="slam_cue_bids",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="systemcard",
            name="slam_gerber",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="systemcard",
            name="slam_rkcb",
            field=models.BooleanField(default=False),
        ),
    ]
