# Generated by Django 5.2.1 on 2025-11-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0075_alter_user_managers_remove_user_covid_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useradditionalinfo',
            name='last_registration_invite_sent',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Registration Invite Sent'),
        ),
    ]
