# Generated by Django 5.2.1 on 2025-10-28 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("masterpoints", "0002_auto_20200322_1537"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChargeType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_mpc_id", models.PositiveIntegerField(unique=True)),
                ("type_name", models.CharField(max_length=50)),
                (
                    "fee_including_gst",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("show_on_invoice", models.BooleanField(default=True)),
                ("is_gst_taxable", models.BooleanField(default=True)),
                (
                    "invoice_words",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("show_on_price_list", models.BooleanField(default=True)),
                (
                    "price_list_sequence",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "mps_or_player",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
            ],
        ),
    ]
