# Generated by Django 5.2.1 on 2025-11-04 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterpoints', '0002_auto_20200322_1537'),
        ('organisations', '0091_alter_organisation_old_mpc_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_mpc_id', models.PositiveIntegerField(unique=True)),
                ('type_name', models.CharField(max_length=50)),
                ('fee_including_gst', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('show_on_invoice', models.BooleanField(default=True)),
                ('is_gst_taxable', models.BooleanField(default=True)),
                ('invoice_words', models.CharField(blank=True, max_length=50, null=True)),
                ('show_on_price_list', models.BooleanField(default=True)),
                ('price_list_sequence', models.PositiveIntegerField(blank=True, null=True)),
                ('mps_or_player', models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GreenPointAchievementBand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_mpc_id', models.PositiveIntegerField()),
                ('low_points', models.DecimalField(decimal_places=2, max_digits=10)),
                ('high_points', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_mpc_id', models.PositiveIntegerField(db_index=True)),
                ('period_month', models.PositiveIntegerField()),
                ('period_year', models.PositiveIntegerField()),
                ('period_end', models.DateTimeField()),
                ('is_current', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_mpc_id', models.PositiveIntegerField(db_index=True)),
                ('rank_name', models.CharField(max_length=15)),
                ('rank_old_name', models.CharField(max_length=15)),
                ('rank_sequence', models.CharField(max_length=1)),
                ('total_needed', models.PositiveIntegerField()),
                ('red_gold_needed', models.PositiveIntegerField()),
                ('gold_needed', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ClubMembershipHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_mpc_id', models.PositiveIntegerField()),
                ('billing_month', models.PositiveIntegerField()),
                ('billing_year', models.PositiveIntegerField()),
                ('old_mpc_club_id', models.PositiveIntegerField()),
                ('home_members', models.PositiveIntegerField()),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organisations.organisation')),
            ],
            options={
                'verbose_name_plural': 'Club Membership Histories',
            },
        ),
        migrations.CreateModel(
            name='MasterpointEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_mpc_id', models.PositiveIntegerField(unique=True)),
                ('event_name', models.CharField(max_length=50)),
                ('event_code', models.CharField(max_length=15)),
                ('mp_colour', models.CharField(max_length=1)),
                ('comments', models.TextField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('billing_club_id', models.IntegerField(null=True)),
                ('t_grade', models.CharField(blank=True, max_length=3, null=True)),
                ('grade', models.CharField(blank=True, max_length=3, null=True)),
                ('gold_point_event_tier', models.CharField(blank=True, max_length=3, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('billing_organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organisations.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='MPBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_mpc_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('mps_submitted_green', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mps_submitted_red', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mps_submitted_gold', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('old_mpc_posted_by_user_id', models.IntegerField(blank=True, null=True)),
                ('posted_date', models.DateTimeField()),
                ('source', models.CharField(choices=[('C', 'Club'), ('E', 'Event')], max_length=1)),
                ('old_mpc_event_or_club_id', models.IntegerField()),
                ('posting_month', models.IntegerField(blank=True, null=True)),
                ('posting_year', models.IntegerField(blank=True, null=True)),
                ('is_mccutcheon_eligible', models.BooleanField()),
                ('is_approved', models.BooleanField()),
                ('uploaded_comments', models.TextField(blank=True, null=True)),
                ('admin_comments', models.TextField(blank=True, null=True)),
                ('is_charged', models.BooleanField()),
                ('authorisation_number', models.CharField(blank=True, max_length=100, null=True)),
                ('uploaded_filename', models.CharField(blank=True, max_length=100, null=True)),
                ('how_submitted', models.CharField(max_length=1)),
                ('event_month', models.CharField(blank=True, max_length=3, null=True)),
                ('check_flag', models.BooleanField(default=False)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organisations.organisation')),
                ('masterpoint_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masterpoints.masterpointevent')),
            ],
            options={
                'verbose_name_plural': 'MP Batches',
            },
        ),
        migrations.CreateModel(
            name='MPTran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_mpc_id', models.PositiveIntegerField(db_index=True)),
                ('old_mpc_player_id', models.PositiveIntegerField()),
                ('system_number', models.PositiveIntegerField(db_index=True)),
                ('mp_colour', models.CharField(choices=[('G', 'Green'), ('R', 'Red'), ('Y', 'Gold')], max_length=1)),
                ('mp_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('source', models.CharField(choices=[('C', 'Club'), ('E', 'Event')], max_length=1)),
                ('old_mp_batch_id', models.PositiveIntegerField()),
                ('is_approved', models.BooleanField()),
                ('mp_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterpoints.mpbatch')),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_mpc_id', models.PositiveIntegerField()),
                ('system_number', models.PositiveIntegerField()),
                ('record_date', models.DateTimeField()),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masterpoints.period')),
                ('rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masterpoints.rank')),
            ],
        ),
    ]
