# Generated by Django 5.2.1 on 2025-10-29 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("masterpoints", "0002_auto_20200322_1537"),
        ("organisations", "0090_organisation_old_mpc_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChargeType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_mpc_id", models.PositiveIntegerField(unique=True)),
                ("type_name", models.CharField(max_length=50)),
                (
                    "fee_including_gst",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("show_on_invoice", models.BooleanField(default=True)),
                ("is_gst_taxable", models.BooleanField(default=True)),
                (
                    "invoice_words",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("show_on_price_list", models.BooleanField(default=True)),
                (
                    "price_list_sequence",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "mps_or_player",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GreenPointAchievementBand",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_mpc_id", models.PositiveIntegerField()),
                ("low_points", models.FloatField()),
                ("high_points", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Period",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_mpc_id", models.PositiveIntegerField()),
                ("period_month", models.PositiveIntegerField()),
                ("period_year", models.PositiveIntegerField()),
                ("period_end", models.DateTimeField()),
                ("is_current", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Rank",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_mpc_id", models.PositiveIntegerField()),
                ("rank_name", models.CharField(max_length=15)),
                ("rank_old_name", models.CharField(max_length=15)),
                ("rank_sequence", models.CharField(max_length=1)),
                ("total_needed", models.PositiveIntegerField()),
                ("red_gold_needed", models.PositiveIntegerField()),
                ("gold_needed", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="MasterpointEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_mpc_id", models.PositiveIntegerField(unique=True)),
                ("event_name", models.CharField(max_length=50)),
                ("event_code", models.CharField(max_length=15)),
                ("mp_colour", models.CharField(max_length=1)),
                ("comments", models.TextField(blank=True, null=True)),
                ("is_closed", models.BooleanField(default=False)),
                ("billing_club_id", models.IntegerField(null=True)),
                ("t_grade", models.CharField(blank=True, max_length=3, null=True)),
                ("grade", models.CharField(blank=True, max_length=3, null=True)),
                (
                    "gold_point_event_tier",
                    models.CharField(blank=True, max_length=3, null=True),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "billing_organisation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organisations.organisation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_mpc_id", models.PositiveIntegerField()),
                ("system_number", models.PositiveIntegerField()),
                ("record_date", models.DateTimeField()),
                (
                    "period",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="masterpoints.period",
                    ),
                ),
                (
                    "rank",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="masterpoints.rank",
                    ),
                ),
            ],
        ),
    ]
