# Generated by Django 5.2.1 on 2025-11-02 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterpoints', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mptran',
            name='source',
            field=models.CharField(choices=[('C', 'Club'), ('E', 'Event')], max_length=1),
        ),
    ]
