# Generated by Django 5.2.1 on 2025-10-28 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masterpoints", "0003_initial"),
        (
            "organisations",
            "0089_memberclubdetails_organisatio_email_3373b5_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MasterpointEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_mpc_id", models.PositiveIntegerField(unique=True)),
                ("event_name", models.CharField(max_length=50)),
                ("event_code", models.CharField(max_length=15)),
                ("mp_colour", models.CharField(max_length=1)),
                ("comments", models.TextField(blank=True, null=True)),
                ("is_closed", models.BooleanField(default=False)),
                ("billing_club_id", models.PositiveIntegerField()),
                ("t_grade", models.CharField(blank=True, max_length=3, null=True)),
                ("grade", models.CharField(blank=True, max_length=3, null=True)),
                (
                    "gold_point_event_tier",
                    models.CharField(blank=True, max_length=3, null=True),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "billing_organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organisations.organisation",
                    ),
                ),
            ],
        ),
    ]
