# Generated by Django 5.2.1 on 2025-10-30 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masterpoints", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MPBatch",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_mpc_id", models.PositiveIntegerField()),
                ("mps_submitted_green", models.FloatField(blank=True, null=True)),
                ("mps_submitted_red", models.FloatField(blank=True, null=True)),
                ("mps_submitted_gold", models.FloatField(blank=True, null=True)),
                (
                    "old_mpc_posted_by_user_id",
                    models.IntegerField(blank=True, null=True),
                ),
                ("posted_date", models.DateTimeField()),
                ("source", models.CharField(max_length=1)),
                ("event_or_club_id", models.IntegerField()),
                ("posting_month", models.IntegerField()),
                ("posting_year", models.IntegerField()),
                ("is_mccutcheon_eligible", models.BooleanField()),
                ("is_approved", models.BooleanField()),
                ("uploaded_comments", models.TextField()),
                ("admin_comments", models.TextField()),
                ("is_charged", models.BooleanField()),
                ("authorisation_number", models.CharField(max_length=100)),
                ("uploaded_filename", models.CharField(max_length=100)),
                ("how_submitted", models.CharField(max_length=1)),
                ("event_month", models.CharField(max_length=3)),
            ],
            options={
                "verbose_name_plural": "MP Batches",
            },
        ),
    ]
