# Generated by Django 5.2.1 on 2025-11-03 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterpoints', '0004_alter_mptran_source'),
        ('organisations', '0091_alter_organisation_old_mpc_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpbatch',
            name='check_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mpbatch',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organisations.organisation'),
        ),
        migrations.AddField(
            model_name='mpbatch',
            name='masterpoint_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masterpoints.masterpointevent'),
        ),
    ]
