# Generated by Django 5.2.1 on 2025-10-28 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masterpoints", "0004_masterpointevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="masterpointevent",
            name="billing_club_id",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
