# Generated by Django 5.2.1 on 2025-10-30 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masterpoints", "0004_mpbatch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mpbatch",
            name="old_mpc_id",
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
