# Generated by Django 5.2.1 on 2025-11-03 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterpoints', '0005_mpbatch_check_flag_mpbatch_club_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpbatch',
            name='source',
            field=models.CharField(choices=[('C', 'Club'), ('E', 'Event')], max_length=1),
        ),
    ]
