# Generated by Django 5.2.1 on 2025-10-28 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masterpoints", "0005_alter_masterpointevent_billing_club_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="masterpointevent",
            name="billing_club_id",
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
