# Generated by Django 5.2.1 on 2025-10-30 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masterpoints", "0005_alter_mpbatch_old_mpc_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mpbatch",
            name="event_month",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
