# Generated by Django 5.2.1 on 2025-11-03 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterpoints', '0006_alter_mpbatch_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mpbatch',
            old_name='event_or_club_id',
            new_name='old_mpc_event_or_club_id',
        ),
    ]
