# Generated by Django 5.2.1 on 2025-10-28 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masterpoints", "0007_alter_masterpointevent_added_by"),
        (
            "organisations",
            "0089_memberclubdetails_organisatio_email_3373b5_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="masterpointevent",
            name="billing_club_id",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="masterpointevent",
            name="billing_organisation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="organisations.organisation",
            ),
        ),
    ]
