# Generated by Django 5.2.1 on 2025-10-30 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masterpoints", "0007_alter_mpbatch_admin_comments_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mpbatch",
            name="uploaded_filename",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
