# Generated by Django 5.2.1 on 2025-11-03 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterpoints', '0007_rename_event_or_club_id_mpbatch_old_mpc_event_or_club_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mptran',
            name='mp_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterpoints.mpbatch'),
        ),
    ]
