# Generated by Django 5.2.1 on 2025-10-30 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masterpoints", "0008_alter_mpbatch_uploaded_filename"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mpbatch",
            name="posting_month",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mpbatch",
            name="posting_year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
