# Generated by Django 5.2.1 on 2025-10-30 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masterpoints", "0009_alter_mpbatch_posting_month_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mpbatch",
            name="old_mpc_id",
            field=models.PositiveIntegerField(db_index=True, unique=True),
        ),
        migrations.CreateModel(
            name="MPTrans",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_mpc_id", models.PositiveIntegerField()),
                ("old_mpc_player_id", models.PositiveIntegerField()),
                ("system_number", models.PositiveIntegerField()),
                ("mp_colour", models.CharField(max_length=1)),
                ("mp_amount", models.FloatField()),
                ("source", models.CharField(max_length=1)),
                ("old_mp_batch_id", models.PositiveIntegerField()),
                ("is_approved", models.BooleanField()),
                (
                    "mp_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="masterpoints.mpbatch",
                    ),
                ),
            ],
        ),
    ]
