# Generated by Django 5.2.1 on 2025-10-30 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("masterpoints", "0010_alter_mpbatch_old_mpc_id_mptrans"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MPTrans",
            new_name="MPTran",
        ),
    ]
