# Generated by Django 5.2.1 on 2025-10-30 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masterpoints", "0011_rename_mptrans_mptran"),
    ]

    operations = [
        migrations.AlterField(
            model_name="greenpointachievementband",
            name="high_points",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="greenpointachievementband",
            name="low_points",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="mpbatch",
            name="mps_submitted_gold",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="mpbatch",
            name="mps_submitted_green",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="mpbatch",
            name="mps_submitted_red",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="mptran",
            name="mp_amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="mptran",
            name="mp_colour",
            field=models.CharField(
                choices=[("G", "Green"), ("R", "Red"), ("Y", "Gold")], max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="mptran",
            name="system_number",
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
