# Generated by Django 5.2.1 on 2025-10-30 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masterpoints", "0012_alter_greenpointachievementband_high_points_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mptran",
            name="old_mpc_id",
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
