# Generated by Django 5.2.1 on 2025-10-30 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masterpoints", "0013_alter_mptran_old_mpc_id"),
        ("organisations", "0090_organisation_old_mpc_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClubMembershipHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_mpc_id", models.PositiveIntegerField()),
                ("billing_month", models.PositiveIntegerField()),
                ("billing_year", models.PositiveIntegerField()),
                ("old_mpc_club_id", models.PositiveIntegerField()),
                ("home_members", models.PositiveIntegerField()),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organisations.organisation",
                    ),
                ),
            ],
        ),
    ]
