# Generated by Django 5.2.1 on 2025-10-30 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masterpoints", "0014_clubmembershiphistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="period",
            name="old_mpc_id",
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name="rank",
            name="old_mpc_id",
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
