"""Generated by utils/cgit/cgit_util_generate_admin_file on 2022-01-24 14:26:19.559531"""

from django.contrib import admin
from .models import (
    Forum,
    Post,
    Comment1,
    Comment2,
    LikePost,
    LikeComment1,
    LikeComment2,
    ForumFollow,
)


@admin.register(Forum)
class ForumAdmin(admin.ModelAdmin):
    """Admin class for model Forum"""

    search_fields = ["title"]


@admin.register(Post)
class PostAdmin(admin.ModelAdmin):
    """Admin class for model Post"""

    search_fields = ["author"]
    autocomplete_fields = [
        "forum",
    ]


@admin.register(Comment1)
class Comment1Admin(admin.ModelAdmin):
    """Admin class for model Comment1"""

    search_fields = ["author"]
    autocomplete_fields = [
        "post",
    ]


@admin.register(Comment2)
class Comment2Admin(admin.ModelAdmin):
    """Admin class for model Comment2"""

    search_fields = ["author"]
    autocomplete_fields = [
        "post",
        "comment1",
    ]


@admin.register(LikePost)
class LikePostAdmin(admin.ModelAdmin):
    """Admin class for model LikePost"""

    autocomplete_fields = [
        "post",
    ]


@admin.register(LikeComment1)
class LikeComment1Admin(admin.ModelAdmin):
    """Admin class for model LikeComment1"""

    autocomplete_fields = [
        "comment1",
    ]


@admin.register(LikeComment2)
class LikeComment2Admin(admin.ModelAdmin):
    """Admin class for model LikeComment2"""

    autocomplete_fields = [
        "comment2",
    ]


@admin.register(ForumFollow)
class ForumFollowAdmin(admin.ModelAdmin):
    """Admin class for model ForumFollow"""

    autocomplete_fields = [
        "user",
        "forum",
    ]
