"""Generated by utils/cgit/cgit_util_generate_admin_file on 2025-10-30 13:19:56.883818"""

from django.contrib import admin
from .models import (
    ChargeType,
    MasterpointEvent,
    GreenPointAchievementBand,
    Rank,
    Period,
    Promotion,
    MPBatch,
    MPTran,
    ClubMembershipHistory,
)


class MasterpointEventAdmin(admin.ModelAdmin):
    """Admin class for model MasterpointEvent"""

    autocomplete_fields = [
        "billing_organisation",
        "added_by",
    ]


class PromotionAdmin(admin.ModelAdmin):
    """Admin class for model Promotion"""

    autocomplete_fields = [
        "rank",
        "period",
    ]


class ClubMembershipHistoryAdmin(admin.ModelAdmin):
    """Admin class for model ClubMembershipHistory"""

    autocomplete_fields = [
        "club",
    ]


class MPTranAdmin(admin.ModelAdmin):
    """Admin class for model MPTran"""

    autocomplete_fields = [
        "mp_batch",
    ]


class MPBatchAdmin(admin.ModelAdmin):
    """Admin class for model MPBatch"""

    search_fields = [
        "=old_mpc_id",
    ]

    list_filter = (
        "source",
        "is_approved",
        "is_charged",
    )


class RankAdmin(admin.ModelAdmin):
    """Admin class for model Rank"""

    search_fields = [
        "old_mpc_id",
    ]


class PeriodAdmin(admin.ModelAdmin):
    """Admin class for model Period"""

    search_fields = ["old_mpc_id"]


admin.site.register(ChargeType)
admin.site.register(MasterpointEvent, MasterpointEventAdmin)
admin.site.register(GreenPointAchievementBand)
admin.site.register(Rank, RankAdmin)
admin.site.register(Period, PeriodAdmin)
admin.site.register(Promotion, PromotionAdmin)
admin.site.register(MPBatch, MPBatchAdmin)
admin.site.register(MPTran, MPTranAdmin)
admin.site.register(ClubMembershipHistory, ClubMembershipHistoryAdmin)
