"""Generated by utils/cgit/cgit_util_generate_admin_file on 2025-10-30 13:19:56.883818"""

from django.contrib import admin
from django.utils.html import format_html

from accounts.models import User, UnregisteredUser
from utils.views.cobalt_django_admin import link_to_user_or_unregistered_user
from .models import (
    ChargeType,
    MasterpointEvent,
    GreenPointAchievementBand,
    Rank,
    Period,
    Promotion,
    MPBatch,
    MPTran,
    ClubMembershipHistory,
)


class MasterpointEventAdmin(admin.ModelAdmin):
    """Admin class for model MasterpointEvent"""

    autocomplete_fields = [
        "billing_organisation",
        "added_by",
    ]


class PromotionAdmin(admin.ModelAdmin):
    """Admin class for model Promotion"""

    readonly_fields = ("linked_user",)

    autocomplete_fields = [
        "rank",
        "period",
    ]

    search_fields = ["system_number"]

    def linked_user(self, instance):
        """ link to user, needs readonly_fields = ("linked_user",) added above """

        return link_to_user_or_unregistered_user(instance.system_number)

    linked_user.short_description = "Link to User"

class ClubMembershipHistoryAdmin(admin.ModelAdmin):
    """Admin class for model ClubMembershipHistory"""

    autocomplete_fields = [
        "club",
    ]


class MPTranAdmin(admin.ModelAdmin):
    """Admin class for model MPTran"""

    autocomplete_fields = [
        "mp_batch",
    ]

    readonly_fields = ("linked_user",)

    def linked_user(self, instance):
        """ link to user, needs readonly_fields = ("linked_user",) added above """

        return link_to_user_or_unregistered_user(instance.system_number)

    linked_user.short_description = "Link to User"

class MPBatchAdmin(admin.ModelAdmin):
    """Admin class for model MPBatch"""

    search_fields = [
        "=old_mpc_id",
    ]

    list_filter = (
        "source",
        "is_approved",
        "is_charged",
    )


class RankAdmin(admin.ModelAdmin):
    """Admin class for model Rank"""

    search_fields = [
        "old_mpc_id",
    ]


class PeriodAdmin(admin.ModelAdmin):
    """Admin class for model Period"""

    search_fields = ["old_mpc_id"]


admin.site.register(ChargeType)
admin.site.register(MasterpointEvent, MasterpointEventAdmin)
admin.site.register(GreenPointAchievementBand)
admin.site.register(Rank, RankAdmin)
admin.site.register(Period, PeriodAdmin)
admin.site.register(Promotion, PromotionAdmin)
admin.site.register(MPBatch, MPBatchAdmin)
admin.site.register(MPTran, MPTranAdmin)
admin.site.register(ClubMembershipHistory, ClubMembershipHistoryAdmin)
