"""Generated by utils/cgit/cgit_util_generate_admin_file on 2022-01-24 12:15:50.068914"""

from django.contrib import admin

from utils.views.cobalt_django_admin import link_to_user_or_unregistered_user
from .models import (
    SessionType,
    SessionTypePaymentMethod,
    SessionTypePaymentMethodMembership,
    Session,
    SessionEntry,
    SessionMiscPayment,
)


@admin.register(SessionType)
class SessionTypeAdmin(admin.ModelAdmin):
    """Admin class for model SessionType"""

    search_fields = ["name", "organisation"]
    autocomplete_fields = [
        "organisation",
    ]


@admin.register(SessionTypePaymentMethod)
class SessionTypePaymentMethodAdmin(admin.ModelAdmin):
    """Admin class for model SessionTypePaymentMethod"""

    search_fields = ["name", "organisation"]
    autocomplete_fields = [
        "session_type",
        "payment_method",
    ]


@admin.register(SessionTypePaymentMethodMembership)
class SessionTypePaymentMethodMembershipAdmin(admin.ModelAdmin):
    """Admin class for model SessionTypePaymentMethodMembership"""

    search_fields = ["membership"]
    autocomplete_fields = [
        "session_type_payment_method",
        "membership",
    ]


@admin.register(Session)
class SessionAdmin(admin.ModelAdmin):
    """Admin class for model Session"""

    search_fields = ["director", "venue"]
    autocomplete_fields = [
        "director",
        "session_type",
        "venue",
    ]


@admin.register(SessionEntry)
class SessionEntryAdmin(admin.ModelAdmin):
    """Admin class for model SessionEntry"""

    search_fields = ["player"]
    autocomplete_fields = [
        "session",
        "org_tran",
        "member_tran",
        "payment_method",
    ]
    readonly_fields = ("linked_user",)

    def linked_user(self, instance):
        """ link to user, needs readonly_fields = ("linked_user",) added above """

        return link_to_user_or_unregistered_user(instance.system_number)

    linked_user.short_description = "Link to User"

class MemberOrganisationLinkAdmin(admin.ModelAdmin):
    """Admin class for model MemberOrganisationLink"""

    autocomplete_fields = [
        "member_transaction",
        "organisation_transaction",
    ]


@admin.register(SessionMiscPayment)
class SessionMiscPaymentAdmin(admin.ModelAdmin):
    """Admin class for model SessionMiscPayment"""

    search_fields = ["system_number"]

    autocomplete_fields = [
        "session_entry",
    ]
