"""Generated by /usr/local/bin/cgit_util_generate_admin_file on 2023-04-02 14:45:42.600208"""

from django.contrib import admin
from .models import XeroCredentials, XeroInvoice


admin.site.register(XeroCredentials)
admin.site.register(XeroInvoice)
