# Generated by Django 5.2.1 on 2025-06-24 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0087_add_memberclubdetails_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="memberclubdetails",
            name="org_mcd_email_idx",
        ),
        migrations.RemoveIndex(
            model_name="memberclubdetails",
            name="org_mcd_bounce_idx",
        ),
        migrations.RemoveIndex(
            model_name="memberclubdetails",
            name="org_mcd_sysnum_idx",
        ),
    ]
