# Generated by Django 5.2.1 on 2025-06-24 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0088_remove_memberclubdetails_org_mcd_email_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="memberclubdetails",
            index=models.Index(fields=["email"], name="organisatio_email_3373b5_idx"),
        ),
        migrations.AddIndex(
            model_name="memberclubdetails",
            index=models.Index(
                fields=["email_hard_bounce"], name="organisatio_email_h_6f612c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="memberclubdetails",
            index=models.Index(
                fields=["system_number"], name="organisatio_system__88829a_idx"
            ),
        ),
    ]
