# Generated by Django 5.2.1 on 2025-10-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "organisations",
            "0089_memberclubdetails_organisatio_email_3373b5_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="old_mpc_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
