# Generated by Django 5.2.1 on 2025-10-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0090_organisation_old_mpc_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="old_mpc_id",
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
