# Generated by Django 5.2.8 on 2026-02-23 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0091_alter_organisation_old_mpc_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memberclubdetails",
            name="latest_membership",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="organisations.membermembershiptype",
                verbose_name="Active Membership",
            ),
        ),
    ]
