# Generated by Django 5.2.1 on 2025-07-27 19:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0009_slug_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="Error500",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "error_date_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Error Datetime"
                    ),
                ),
                ("user", models.CharField(blank=True, max_length=100, null=True)),
                ("summary", models.CharField(blank=True, max_length=200, null=True)),
                ("error", models.TextField()),
            ],
        ),
    ]
