# Generated by Django 5.2.8 on 2026-02-27 23:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0010_error500"),
    ]

    operations = [
        migrations.CreateModel(
            name="BatchStatus",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("command", models.CharField(max_length=100, verbose_name="Command")),
                (
                    "run_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Run Date"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Started", "Running"),
                            ("Success", "Completed successfully"),
                            ("Failed", "Failed"),
                        ],
                        default="Started",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                ("summary", models.TextField(blank=True, verbose_name="Summary")),
            ],
            options={
                "verbose_name_plural": "Batch statuses",
                "ordering": ["-run_date"],
            },
        ),
    ]
