# Generated by Django 5.2.12 on 2026-04-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0011_batchstatus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batch",
            name="node",
            field=models.CharField(
                default="NOTSET", max_length=50, verbose_name="Node running job"
            ),
        ),
    ]
