# Generated by Django 5.2.12 on 2026-04-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0056_add_post_office_email_message_id_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batchid",
            name="batch_type",
            field=models.CharField(
                choices=[
                    ("ADM", "Admin"),
                    ("COM", "Comms"),
                    ("CNG", "Congress"),
                    ("EVT", "Event"),
                    ("MBR", "Member"),
                    ("MLT", "Multi-event"),
                    ("RES", "Results"),
                    ("ENT", "Entry"),
                    ("SES", "Session"),
                    ("UNK", "Unknown"),
                ],
                default="UNK",
                max_length=3,
                verbose_name="Batch Type",
            ),
        ),
    ]
