# Generated by Django 5.2.12 on 2026-04-07 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0056_add_post_office_email_message_id_index"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="snooper",
            name="limited_notifications",
        ),
    ]
