# Generated by Django 5.2.12 on 2026-04-13 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0057_remove_snooper_limited_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="snooper",
            name="limited_notifications",
            field=models.BooleanField(
                default=False, verbose_name="Limited Notifications"
            ),
        ),
    ]
